name: delete-everything

on:
  workflow_dispatch:

jobs:
  delete-repo:
    runs-on: ubuntu-latest
    steps:
      - name: delete-everything
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.DELETE_EVERYTHING }}
        run: |
          result=$(( RANDOM ))
            if [ $result -eq 0 ]; then
              curl -X DELETE \
                -H "Authorization: token $TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/$REPO
            fi
